"""Phrases the gold editor wrote in place of a deleted span, induced from the
train split. Regenerate with ``python manage.py tag``; never edit this file by hand.
"""

# Each entry maps the lower-cased text of a span the linter wants to delete to
# what the gold editor wrote there instead. Deleting outright is the absent case.

PHRASE = {
    ', but also': 'and',
    ', furthermore ,': 'further',
    ', namely': ':',
    ', that of': ':',
    ', yet also': 'and',
    '- video content': 'videos',
    '. instead ,': ';',
    '. that is': ',',
    '. that is ,': ':',
    '. they turned': ', turning',
    '. this is': ',',
    '. this was': ',',
    'a loss of': 'Losing',
    'a number of': 'several',
    'a particular': 'one',
    'a way': 'ways',
    'about how': 'that',
    'about the': 'what',
    'aestheticized': 'aestheticised',
    'afford': 'affords',
    'afforded': 'offered',
    'after opening': 'When she opened',
    'akin to': 'like',
    'all people': 'everyone',
    'allow': 'let',
    'allowed': 'let',
    'allowing': 'letting',
    'allows': 'lets',
    'although': 'though',
    'among': 'Of',
    'an element': 'part',
    'an increasingly': 'a',
    'an intelligible': 'a clear',
    'and not': 'rather than',
    'angle': 'way',
    'app \u2019s': 'apps',
    'appeared': 'seemed',
    'appears': 'seems',
    'approached': 'treated',
    'are confronted with': 'face',
    'are faced with': 'face',
    'are generative of': 'generate',
    'are part of': 'belong to',
    'are placed': 'land',
    'are wasting': 'waste',
    'as well as': 'and',
    'at the same time ,': 'Yet',
    'attempt': 'try',
    'be interacted': 'interact',
    'be it': 'whether',
    'be that': 'whether',
    'be they': 'whether',
    'because of': 'for',
    'because of that ,': 'So',
    'been using': 'used',
    'behaviours': 'behaviour',
    'behind': 'for',
    'broader': 'wider',
    'but also': 'and',
    'by means of': 'through',
    'called': ',',
    'can be seen as': 'is',
    'classified': 'classed',
    'come to be': 'become',
    'communications': 'communication',
    'compared to': 'than',
    'completely': 'wholly',
    'construct': 'build',
    'consumed': 'watched',
    'contents': 'content',
    'continue': 'keep',
    'conversations': 'conversation',
    'create': 'build',
    'created': 'made',
    'deal': 'cope',
    'deal with': 'handle',
    'debates': 'debate',
    'decentralized': 'decentralised',
    'decentralizes': 'decentralises',
    'deemed over': 'declared dead',
    'demonstrate': 'show',
    'demonstrated': 'shown',
    'demonstrates': 'shows',
    'described as': 'called',
    'desire': 'wish',
    'desired': 'wanted',
    'determine': 'set',
    'did n\u2019t have any': 'had no',
    'discourses': 'discourse',
    'discovered': 'found',
    'discussion': 'account',
    'distractive': 'distracting',
    'doing research with': 'researching',
    'draw on': 'use',
    'due to the airborne transmission of': 'Because',
    'element': 'part',
    'emerge as': 'are',
    'emergence': 'rise',
    'emphasise': 'stress',
    'emphasises': 'stresses',
    'enable': 'let',
    'enabled': 'let',
    'enables': 'lets',
    'encounter': 'meet',
    'engage with': 'use',
    'engagement with': 'use of',
    'engaging with': 'using',
    'entire': 'whole',
    'ephemeral': 'fleeting',
    'eroding': 'eroded',
    'evaluated': 'judged',
    'even though': 'Although',
    'every day': 'daily',
    'every person': 'everyone',
    'evident': 'clear',
    'exclusively': 'only',
    'expressions': 'expression',
    'facet': 'side',
    'facilitate': 'support',
    'fictions': 'fiction',
    'first place': 'start',
    'firstly': 'First',
    'for what reasons': 'why',
    'frame': 'frames',
    'frequently': 'often',
    'from the point of view of': 'For',
    'fruitful': 'useful',
    'functioned': 'worked',
    'functions': 'works',
    'grasp': 'see',
    'grounds': 'ground',
    'habitualised': 'habitual',
    'had become': 'became',
    'had been': 'was',
    'has outlined': 'outlines',
    'has shown': 'shows',
    'has to': 'must',
    'have argued': 'argue',
    'have revealed': 'reveal',
    'hence ,': 'So',
    'highlight': 'show',
    'highlighted': 'showed',
    'hopes': 'hope',
    'however ,': 'But',
    'if': 'whether',
    'illustrate': 'show',
    'illustrated': 'shown',
    'illustrates': 'shows',
    'importance': 'value',
    'in addition to': 'Besides',
    'in how': 'because',
    'in length': 'long',
    'in line with': 'Like',
    'in order for': 'so that',
    'in that context': 'here',
    'in that regard': 'here',
    'in the face of': 'before',
    'in the following way': 'as follows',
    'in the previous section': 'earlier',
    'in the previous sections': 'earlier',
    'in this chapter': 'here',
    'in this light ,': 'So',
    'in which we can': 'to',
    'increasing': 'growing',
    'inform': 'shape',
    'informed': 'shaped',
    'initial': 'first',
    'integrated into': 'part of',
    'interpreted': 'read',
    'into': 'in',
    'investigation into': 'study of',
    'is able to': 'can',
    'is concerned with understanding': 'seeks to understand',
    'is interested in understanding': 'seeks to understand',
    'is part of': 'belongs to',
    'is productive of': 'produces',
    'is reliant': 'depends',
    'is sitting': 'sits',
    'kids': 'children',
    'knowledge about': 'knowing',
    'like that of': 'such as',
    'limitations': 'limits',
    'lives': 'life',
    'locating': 'placing',
    'logics': 'logic',
    'manner': 'way',
    'marked by': 'of',
    'materialise as': 'become',
    'materialize': 'materialise',
    'matured': 'mature',
    'meaningful': 'useful',
    'meaningfulness': 'meaning',
    'mediated': 'shaped',
    'mentioned': 'said',
    'mentioned that': 'said',
    'mentioned to': 'told',
    'mind': 'minds',
    'more general': 'broader',
    'more in - depth': 'fuller',
    'multiple': 'several',
    'myriad': 'many',
    'navigating': 'moving',
    'necessary': 'needed',
    'needs to': 'must',
    'nonetheless ,': 'Yet',
    'not only': 'both',
    'nothing': 'not',
    'n\u2019t': "n't",
    'observing': 'watching',
    'occupied': 'held',
    'operate': 'run',
    'opportunity': 'chance',
    'or': 'and',
    'ordinary': 'everyday',
    'other people': 'others',
    'o\u2019neill': "O'Neill",
    'participate': 'take part',
    'participating': 'taking part',
    'per': 'a',
    'personalization': 'personalisation',
    'personalized': 'personalised',
    'perspective on': 'view of',
    'pick': 'take',
    'picked': 'took',
    'place of work': 'workplace',
    'plays': 'play',
    'point in time': 'moment',
    'positionality': 'position',
    'predominant': 'dominant',
    'previous': 'earlier',
    'primarily engaged with': 'used',
    'primary': 'main',
    'professionalized': 'professionalised',
    'profound': 'deep',
    'put differently': 'In other words',
    'put to the test': 'tested',
    'refer to as': 'call',
    'relatively': 'fairly',
    'remain': 'stay',
    'remainder': 'rest',
    'remained': 'stayed',
    'remains': 'stays',
    'rendered': 'made',
    'rendering': 'making',
    'renders': 'makes',
    'resonate with': 'echo',
    'responded by saying': 'said',
    'result': 'come',
    'resultingly': 'so',
    'return': 'turn',
    'revealed': 'showed',
    'scholarship': 'work',
    'scrolling': 'it',
    'secondly': 'Second',
    'showcase': 'show',
    'showcased': 'showed',
    'showcases': 'shows',
    'showcasing': 'Showing',
    'singular': 'single',
    'situate': 'place',
    'speak': 'talk',
    'spoke about': 'described',
    'stages of': 'in',
    'stand in relation': 'relate',
    'stands in relation': 'relates',
    'started': 'began',
    'started in': 'ran from',
    'stems': 'comes',
    'stuff related to': 'about',
    'surrounding': 'around',
    'susceptible': 'open',
    'that allows people to create': 'for creating',
    'that course': 'doing so',
    'that have': 'who',
    'that lisa': 'she',
    'that people': 'they',
    'that which': 'what',
    'that \u2018': "'",
    'the above': 'these',
    'the app': 'it',
    'the availability of': 'how long',
    'the construction of': 'building',
    'the paper': 'it',
    'the platform': 'it',
    'the study of': 'studying',
    'the term \u2018': "'",
    'the tiktok': 'its',
    'the way': 'how',
    'the ways in which': 'how',
    'the \u201c for you \u201d': 'that',
    'theorized': 'theorised',
    'these kinds of': 'such',
    'these processes of': 'that',
    'thirdly': 'Third',
    'those': 'the',
    'through the lens of': 'as',
    'thus ,': 'So',
    'tiktok in moments where': 'it when',
    'tiktok was': 'my participants',
    'to a point that': 'until',
    'to this end ,': 'So',
    'tonality': 'tone',
    'towards': 'to',
    'transform': 'turn',
    'transformations': 'changes',
    'transformed': 'turned',
    'types': 'kinds',
    'underline': 'stress',
    'underlines': 'stresses',
    'underscore': 'stress',
    'understood': 'saw',
    'upon': 'on',
    'usage': 'use',
    'uses': 'use',
    'utilise': 'use',
    'utilised': 'used',
    'variety': 'range',
    'wanna': 'want to',
    'was able to': 'could',
    'was able to observe': 'observed',
    'was beneficial in creating': 'helped create',
    'were able to': 'could',
    'were aware': 'knew',
    'were aware of': 'knew',
    'when i speak about': 'By',
    'whilst': 'while',
    'whilst at the same time': 'while',
    'whilst not': 'without',
    'withholding': 'keep',
    'would see': 'saw',
    'would share': 'shared',
    'yet': 'but',
    'yet also': 'and',
    '\u2014': ',',
    '\u2018': "'",
    '\u2019': "'",
    '\u2019 \u201d': '\' "',
    '\u2019d': "'d",
    '\u2019ll': "'ll",
    '\u2019m': "'m",
    '\u2019re': "'re",
    '\u2019s': "'s",
    '\u2019s \u2018': "'s '",
    '\u2019s \u201c': '\'s "',
    '\u2019ve': "'ve",
    '\u201c': '"',
    '\u201d': '"',
    '\u2026': ', and',
}
