"""Support-verb collapse rates, induced from the gold corpus.

Generated by ``evidence/induce.py``; do not edit by hand. Regenerate with::

    python manage.py induce

Each entry is ``"<light verb> <noun lemma>": (collapse rate, times seen)``,
where the rate is the share of occurrences whose noun did not survive into the
gold edit. The rate is used directly as the rule's confidence, so a construction
the gold editor usually leaves alone cannot clear a band threshold. Constructions
absent from this table have no evidence behind them and are refused.

The rate is an upper bound on the true collapse rate: a noun also disappears when
the editor rewrote or dropped the whole sentence for unrelated reasons.
"""

COLLAPSE_RATE = {
    "carry obligation": (0.00, 4),
    "carry work": (0.00, 4),
    "conduct fieldwork": (0.00, 5),
    "conduct interview": (0.00, 5),
    "do esport": (0.00, 10),
    "do research": (0.00, 8),
    "do thing": (0.00, 8),
    "give form": (0.25, 4),
    "give meaning": (0.00, 5),
    "give rise": (0.55, 11),
    "have access": (0.29, 7),
    "have accuracy": (0.25, 4),
    "have app": (0.00, 4),
    "have awareness": (0.42, 12),
    "have consequence": (0.43, 7),
    "have effect": (0.30, 10),
    "have experience": (0.00, 9),
    "have friend": (0.00, 5),
    "have function": (0.29, 7),
    "have impact": (0.55, 11),
    "have implication": (0.00, 4),
    "have interest": (0.14, 7),
    "have laugh": (0.00, 4),
    "have obligation": (0.14, 7),
    "have sense": (0.25, 4),
    "have time": (0.20, 5),
    "have user": (0.00, 4),
    "make argument": (0.17, 6),
    "make decision": (0.42, 12),
    "make meaning": (0.00, 6),
    "make observation": (0.55, 11),
    "make reference": (0.80, 5),
    "make sense": (0.14, 79),
    "make use": (0.00, 7),
    "offer angle": (0.25, 4),
    "offer perspective": (0.20, 5),
    "provide analysis": (0.40, 5),
    "provide answer": (0.17, 6),
    "provide description": (0.83, 6),
    "provide evidence": (0.12, 8),
    "provide insight": (0.33, 6),
    "provide opportunity": (0.91, 11),
    "provide overview": (0.29, 7),
    "provide people": (0.00, 16),
    "provide perspective": (0.60, 5),
    "take approach": (0.25, 4),
    "take break": (0.00, 9),
    "take control": (0.00, 4),
    "take form": (0.00, 5),
    "take place": (0.40, 35),
    "take shape": (0.22, 23),
}
