"""Induce a support-verb allow-list from what the gold editor actually did.

The structural test for a light-verb construction cannot separate "make use of"
from "make sense of": both are a light verb, a noun, and a preposition handing on
the real object. The difference is that one is compositional and the other is an
idiom, and no parse feature reveals which.

Morphology gets most of the way. A nominalisation formed by suffix ("analysis",
"consideration", "description") is reliably compositional, so the rule can fire
on an unseen one. Zero-derived nouns, where the noun and verb share a form
("use", "sense", "care", "note"), are where the idioms live, and there the only
honest evidence is the corpus: did the gold editor collapse this construction
when it had the chance?

This module answers that question by finding every light-verb construction in
the originals and checking what happened to it in the paired edit. The result is
a small table with counts, regenerated rather than argued about.
"""
from collections import Counter, defaultdict

_LIGHT_VERBS = frozenset([
    "make", "take", "give", "have", "do", "conduct", "perform", "provide",
    "offer", "undertake", "carry", "engage", "reach", "hold", "place", "put",
])


def _constructions(doc):
    """Every (light verb, noun) pair in a parse, with the noun's modifiers."""
    for verb in doc:
        if verb.pos_ not in ("VERB", "AUX") or verb.lemma_.lower() not in _LIGHT_VERBS:
            continue
        for child in verb.children:
            if child.dep_ == "dobj" and child.pos_ == "NOUN":
                modifiers = [t.text.lower() for t in child.children
                             if t.dep_ in ("amod", "compound", "nummod")]
                yield verb.lemma_.lower(), child.lemma_.lower(), modifiers


def survey(samples, nlp, on_progress=None) -> dict:
    """How the gold editor treated each light-verb construction it met.

    Args:
        samples: gold :class:`evidence.load.Sample` records.
        nlp: a loaded spaCy pipeline.
        on_progress: called with (index, total, sample).

    Returns:
        ``{"seen", "collapsed", "kept", "modified"}``. ``collapsed`` counts the
        times the noun disappeared from the edit (the construction was resolved
        away); ``kept`` counts the times it survived; ``modified`` counts how
        often the noun carried its own adjectival modifiers, which is what makes
        a collapse destroy content.
    """
    seen, collapsed, kept = Counter(), Counter(), Counter()
    modified = defaultdict(int)
    total = len(samples)
    for i, sample in enumerate(samples, 1):
        if on_progress:
            on_progress(i, total, sample)
        edit_lemmas = {t.lemma_.lower() for t in nlp(sample.edit)}
        for verb, noun, modifiers in _constructions(nlp(sample.original)):
            key = f"{verb} {noun}"
            seen[key] += 1
            if modifiers:
                modified[key] += 1
            if noun in edit_lemmas:
                kept[key] += 1
            else:
                collapsed[key] += 1
    return {"seen": seen, "collapsed": collapsed, "kept": kept, "modified": modified}


def collapse_rate(survey_result: dict, minimum: int = 3) -> list[tuple]:
    """Constructions ordered by how often the gold editor resolved them away."""
    seen, collapsed = survey_result["seen"], survey_result["collapsed"]
    rows = [(key, count, collapsed[key], collapsed[key] / count)
            for key, count in seen.items() if count >= minimum]
    return sorted(rows, key=lambda row: (-row[3], -row[1]))


_TABLE_HEADER = '''"""Support-verb collapse rates, induced from the gold corpus.

Generated by ``evidence/induce.py``; do not edit by hand. Regenerate with::

    python manage.py induce

Each entry is ``"<light verb> <noun lemma>": (collapse rate, times seen)``,
where the rate is the share of occurrences whose noun did not survive into the
gold edit. The rate is used directly as the rule's confidence, so a construction
the gold editor usually leaves alone cannot clear a band threshold. Constructions
absent from this table have no evidence behind them and are refused.

The rate is an upper bound on the true collapse rate: a noun also disappears when
the editor rewrote or dropped the whole sentence for unrelated reasons.
"""

COLLAPSE_RATE = {
'''


def write_table(survey_result: dict, path, minimum: int = 4) -> int:
    """Write the induced collapse-rate table as an importable module."""
    rows = collapse_rate(survey_result, minimum=minimum)
    lines = [_TABLE_HEADER]
    for key, seen, _, rate in sorted(rows):
        lines.append(f'    "{key}": ({rate:.2f}, {seen}),\n')
    lines.append("}\n")
    path.write_text("".join(lines), encoding="utf-8")
    return len(rows)
