CLICHE_REPLACEMENTS = {
    "sheds light on": "clarifies",
    "shed light on": "clarify",
    "calls into question": "questions",
    "call into question": "question",
    "brings to light": "reveals",
    "bring to light": "reveal",
    "plays a role in": "contributes to",
    "play a role in": "contribute to",
    "plays a part in": "contributes to",
    "play a part in": "contribute to",
    "at the forefront of": "leading",
    "in the forefront of": "leading",
    "paradigm shift": "fundamental change",
    "in and of itself": "",
    "suffice it to say": "",
    "suffice to say": "",
    "it stands to reason that": "",
    "each and every": "every",
    "last but not least": "finally",
}

WORD_SUBSTITUTIONS = {
    "utilise": "use",
    "utilises": "uses",
    "utilised": "used",
    "utilising": "using",
    "utilisation": "use",
    "endeavour": "try",
    "endeavours": "tries",
    "endeavoured": "tried",
    "endeavouring": "trying",
    "ascertain": "find out",
    "ascertains": "finds out",
    "ascertained": "found out",
    "notwithstanding": "despite",
    "nevertheless": "but",
    "nonetheless": "but",
    "subsequently": "then",
    "previously": "before",
    "currently": "now",
    "presently": "now",
}
