PHRASE_REPLACEMENTS = {
    # Academic idioms
    "as we find it": "",
    "as we see it": "",
    "as it stands": "",
    "in actual fact": "",
    "in point of fact": "",
    "with this in mind": "",
    "against this backdrop": "",
    "against this background": "",
    "having said that": "",
    "that being said": "",
    "in and of itself": "",
    "having established this": "",
    "the fact that": "that",
    "the way that": "how",
    "the way in which": "how",
    "the manner in which": "how",
    "the means by which": "how",
    "the ways in which": "how",
    "the extent to which": "how far",
    "the degree to which": "how far",
    "and also": "and",
    "but however": "but",
    "in the absence of": "without",
    "in a position to": "able to",
    "in a situation where": "when",
    "from the point of view of": "for",
    "from the perspective of": "for",
    "is of the opinion that": "believes",
    "holds the view that": "believes",
    "takes the view that": "believes",
    # Wordiness (Microsoft style equivalents, previously handled by Vale)
    "in order to": "to",
    "in order that": "so that",
    "due to the fact that": "because",
    "for the reason that": "because",
    "owing to the fact that": "because",
    "on account of the fact that": "because",
    "in the event that": "if",
    "in spite of the fact that": "although",
    "despite the fact that": "although",
    "at this point in time": "now",
    "at the present time": "now",
    "at the current time": "now",
    "during the course of": "during",
    "in the course of": "during",
    "for the purpose of": "to",
    "with the purpose of": "to",
    "for the purposes of": "for",
    "make use of": "use",
    "make reference to": "refer to",
    "make mention of": "mention",
    "give consideration to": "consider",
    "take into consideration": "consider",
    "take into account": "consider",
    "on a regular basis": "regularly",
    "on a daily basis": "daily",
    "on an annual basis": "annually",
    "prior to": "before",
    "subsequent to": "after",
    "with the exception of": "except for",
    "in addition to this": "additionally",
    "as a consequence of": "because of",
    "it should be noted that": "",
    "it is important to note that": "",
    "it is worth noting that": "",
    "it goes without saying that": "",
    "it is clear that": "",
    "it is evident that": "",
    "it is obvious that": "",
    "needless to say": "",
    "as has been noted": "",
    "as mentioned above": "",
    "as discussed above": "",
    "as noted above": "",
    "it is interesting to note that": "",
    "it is worth pointing out that": "",
    "it must be remembered that": "",
    "it cannot be denied that": "",
    "there can be no doubt that": "",
    "it is often the case that": "",
    "as a matter of fact": "",
    "for all intents and purposes": "",
    "in the final analysis": "",
    "when all is said and done": "",
    # Wordy quantifiers and frames
    "in light of the fact that": "because",
    "in view of the fact that": "because",
    "a large number of": "many",
    "a considerable number of": "many",
    "a significant number of": "many",
    "a substantial number of": "many",
    "a great number of": "many",
    "a number of": "several",
    "a great deal of": "much",
    "the majority of": "most",
    "a wide variety of": "many",
    "a wide range of": "many",
    "an array of": "many",
    "with reference to": "about",
    "with respect to": "about",
    "in connection with": "about",
    "by means of": "by",
    "in spite of": "despite",
    "the question as to whether": "whether",
    "as to whether": "whether",
}
